apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-mvp-component-dzbi
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images@sha256:96fa19d494126636ce45c4717307eceb5a629e49a7fd86a2cea92f67966cdcf6
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
